name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create test env
        run: |
          echo "NODE_ENV=test" >> .env
          echo "SESSION_SECRET=test123test123test123test123test123test123te" >> .env
          echo "COOKIE_NAME=sessionid" >> .env
          echo "RPC_URL=https://example.com" >> .env
          echo "WSS_URL=wss://example.com" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
