name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Create .env file
        run: |
          echo "RPC_URL=https://api.mainnet-beta.solana.com" >> .env
          echo "WSS_URL=wss://convincing-wild-mansion.solana-mainnet.quiknode.pro/84e188dafd8e7be7e208d758c2a5d626d7430f95/" >> .env
          echo "SESSION_SECRET=test123test123test123test123test123test123te" >> .env
          echo "NODE_ENV=development" >> .env

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
